version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis_mem
    ports:
      - "6379:6379"
      - "8001:8001"   # RedisInsight UI
    environment:
      - REDIS_ARGS=--save "" --appendonly no
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:7
    container_name: mongo_mem
    ports:
      - "27017:27017"
    command: ["--wiredTigerCacheSizeGB", "1"]
    volumes:
      - mongo_data:/data/db

 
 
  chromadb:
    image: chromadb/chroma:0.5.18
    container_name: chromadb
    ports: ["8000:8000"]
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - ANONYMIZED_TELEMETRY=false
    volumes:
      - ./chroma-data:/chroma/chroma

  neo4j:
    image: neo4j:5.22
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=512m
    ports:
      - "7474:7474" # Browser
      - "7687:7687" # Bolt
    volumes:
      - ./neo4j-data:/data



volumes:
  redis_data:
  mongo_data:
  chroma_data:
